## Vision Encoder
vision_config: ../models/XVLM/configs/config_swinB_224.json

use_clip_vit: False

use_swin: True
image_res: 224
patch_size: 32

## Text Encoder
use_roberta: False
text_config: ../models/XVLM/configs/config_bert.json
text_encoder: bert-base-uncased

## Training
batch_size_test: 12
batch_size_test_text: 64
max_tokens: 40
embed_dim: 256
temp: 0.07
k_test: 256