ARO_image_folder_url: https://drive.google.com/file/d/1KnuPkzIzhxMRg39oY569m0u4Tfyw3g_y/view?usp=sharing
VALSE_image_folder_url: https://drive.google.com/file/d/1rNDEbPlKwQdZrvrPMCXZBiDz9QXTh2La/view?usp=sharing

full_dataset_path: ../datasets/combined_aro_valse.json