ARO_image_folder_url: https://drive.google.com/drive/folders/13x1slntu0R8t-TKsNHpQFUy7YB_pci3w?usp=sharing
VALSE_image_folder_url: https://drive.google.com/drive/folders/1CuGievpfYU9yNLANSOBwZvcIvMBOgacv?usp=sharing

full_dataset_path: datasets/combined_aro_valse.json